#
# env.sh template
#
# this is a template file to be used along with
# `bdbc-session-explorer`, by setting up its default settings.
#
# when working with `bdbc-nwb-packager`, these settings will be mandatory.
#
#
# USAGE
# -----
#
# Copy this file as `env.sh`, and fill in the corresponding info:
#
# - add the file path if it is available.
# - comment out the unavailable info, by prepending the line with a hash (#).
#
# Then, run in each terminal prompt to be used:
#
# ```
# source env.sh
# ```
#

# Path to the directory of the DeepLabCut project
# for estimation of the widefield keypoints.
export MESONET_DLC_PROJECT_DIR=

# Path to the root directory to the session metadata files.
export BDBC_SESSION_ROOT=

# Path to the root directory to the raw-data (intermediate) HDF files.
export BDBC_RAWDATA_ROOT=

# Path to the root directory to the mesoscaler (atlas alignment) HDF files
# in the format `bdbc-atlas-registration` generates.
export BDBC_MESOSCALER_ROOT=

# Path to the root directory to the video files.
export BDBC_VIDEOS_ROOT=

# Path to the DeepLabCut project directories
# for tracking body/face/eye keypooints.
export BDBC_BODYMODEL_DIR=
export BDBC_FACEMODEL_DIR=
export BDBC_EYEMODEL_DIR=

# Path to the root directories for the DeepLabCut tracking results.
# All the results may share the same single root directory.
export BDBC_BODYRESULTS_ROOT=
export BDBC_FACERESULTS_ROOT=
export BDBC_EYERESULTS_ROOT=
export BDBC_PUPILFITTING_ROOT=

# Path to the root directory of the output NWB files.
# It will be automatically generated by `bdbc-nwb-packager`
# if it does not exist.
export BDBC_PUBLICATION_ROOT=
